### ISSUE TITLE
Your mod is using the wrong pack_format in Pack.mcmeta

### ISSUE THREAD

**Issue by BedrockLegends** [DarkRoleplay/Global-Data-and-Resourcepacks#4]
For 1.16.3 and above you need to change pack_format from 5 to 6

**Comment by JTK222** [comment]
The mod works on all 1.16 versions so far, and 1.16.3 can handle format 5 perfectly fine,
especially considering that the mod doesn't even add any affected assets.
For backwards compatibility with 1.16.1 and 1.16.2 this will stay like it is.

**Comment by BedrockLegends** [comment]
"pack_format" requires:

1 in 1.6.1 – 1.8.9
2 in 1.9 – 1.10.2
3 in 1.11 – 1.12.2
4 in 1.13 – 1.14.4
5 in 1.15 – 1.16.1
6 in 1.16.2 – 1.16.3

**Comment by JTK222** [comment]
"requires", the pack format is mostly there to tell the user whether a pack is compatible with their version.
And in some rare cases there is some special code to load models from older pack formats correctly.
Which as said, is completely unimportant if you don't add any assets, in my case I only add language files, so whichever format version turned those into en_us.json rather than en_US.lang is the minimal one I can use without any issues.
